-- Create table ORDERS
CREATE TABLE ORDERS (
    Id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Primary Key
    INVESTORID NUMBER NOT NULL,                                -- Mã nhà đầu tư
    TOTALPRICE NUMBER(18, 2) NOT NULL,                        -- Tổng giá
    FULLNAME VARCHAR2(250) NOT NULL,                          -- Họ và tên
    EMAIL VARCHAR2(250) NOT NULL,                             -- Email
    ADDRESS VARCHAR2(500) NOT NULL,                           -- Địa chỉ
    INVOICEADDRESS VARCHAR2(500) NULL,                        -- Địa chỉ hóa đơn
    CreatedDate TIMESTAMP(7) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, -- Ngày tạo
    LastModifiedDate TIMESTAMP(7) WITH TIME ZONE                              -- Ngày cập nhật cuối
)
/

-- Insert data
INSERT INTO ORDERS (INVESTORID, TOTALPRICE, FULLNAME, EMAIL, ADDRESS, INVOICEADDRESS, CREATEDDATE, LASTMODIFIEDDATE)
VALUES (1, 100000.00, 'Nguyễn Văn A', 'nguyenvana@example.com', '123 Đường ABC, TP.HCM', '123 Đường ABC, TP.HCM', CURRENT_TIMESTAMP, NULL)
/

INSERT INTO ORDERS (INVESTORID, TOTALPRICE, FULLNAME, EMAIL, ADDRESS, INVOICEADDRESS, CREATEDDATE, LASTMODIFIEDDATE)
VALUES (2, 50000.00, 'Trần Thị B', 'tranthib@example.com', '456 Đường DEF, Hà Nội', NULL, CURRENT_TIMESTAMP, NULL)
/

INSERT INTO ORDERS (INVESTORID, TOTALPRICE, FULLNAME, EMAIL, ADDRESS, INVOICEADDRESS, CREATEDDATE, LASTMODIFIEDDATE)
VALUES (3, 75000.00, 'Lê Văn C', 'levanc@example.com', '789 Đường GHI, Đà Nẵng', '789 Đường GHI, Đà Nẵng', CURRENT_TIMESTAMP, NULL)
/
