-- Oracle DDL for Flex.Workflow.Api

CREATE TABLE WF_DEFINITIONS (
  ID            NUMBER(19)      PRIMARY KEY,
  CODE          VARCHAR2(100)   NOT NULL,
  NAME          NVARCHAR2(200)  NOT NULL,
  VERSION       NUMBER(10)      DEFAULT 1 NOT NULL,
  IS_ACTIVE     NUMBER(1)       DEFAULT 1 NOT NULL,
  STEPS         CLOB,
  POLICY        CLOB,
  DESCRIPTION   NVARCHAR2(500),
  UPDATED_AT    TIMESTAMP,
  UPDATED_BY    VARCHAR2(100)
);
CREATE UNIQUE INDEX UX_WF_DEFINITIONS_CODE_VER ON WF_DEFINITIONS(CODE, VERSION);

CREATE TABLE WF_REQUESTS (
  ID              NUMBER(19)     PRIMARY KEY,
  ENTITY_ID       NUMBER(19)     NOT NULL,
  ACTION          VARCHAR2(20)   NOT NULL,
  REQUESTED_DATA  CLOB           NOT NULL,
  COMMENTS        NVARCHAR2(500),
  MAKER_ID        VARCHAR2(100)  NOT NULL,
  REQUESTED_DATE  TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CHECKER_ID      VARCHAR2(100),
  APPROVE_DATE    TIMESTAMP,
  STATUS          VARCHAR2(10),
  DOMAIN          VARCHAR2(50)   NOT NULL,
  WORKFLOW_CODE   VARCHAR2(100)  NOT NULL,
  BUSINESS_ID     VARCHAR2(200),
  CORRELATION_ID  VARCHAR2(100)
);
CREATE INDEX IX_WF_REQUESTS_STATE ON WF_REQUESTS(DOMAIN, WORKFLOW_CODE, ACTION, STATUS);
CREATE INDEX IX_WF_REQUESTS_BIZ ON WF_REQUESTS(BUSINESS_ID);

CREATE TABLE WF_ACTIONS (
  ID          NUMBER(19)     PRIMARY KEY,
  REQUEST_ID  NUMBER(19)     NOT NULL,
  STEP        NUMBER(10)     NOT NULL,
  ACTION      VARCHAR2(20)   NOT NULL,
  ACTOR_ID    VARCHAR2(100)  NOT NULL,
  COMMENT     NVARCHAR2(500),
  EVIDENCE_URL VARCHAR2(500),
  CREATED_AT  TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IX_WF_ACTIONS_REQ_STEP ON WF_ACTIONS(REQUEST_ID, STEP);

CREATE TABLE WF_AUDIT_LOGS (
  ID          NUMBER(19)     PRIMARY KEY,
  REQUEST_ID  NUMBER(19)     NOT NULL,
  EVENT       VARCHAR2(50)   NOT NULL,
  ACTOR_ID    VARCHAR2(100)  NOT NULL,
  METADATA    CLOB,
  PREV_HASH   VARCHAR2(128),
  CURR_HASH   VARCHAR2(128)  NOT NULL,
  CREATED_AT  TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IX_WF_AUDIT_LOGS_REQ ON WF_AUDIT_LOGS(REQUEST_ID);

CREATE TABLE WF_OUTBOX_EVENTS (
  ID           NUMBER(19)    PRIMARY KEY,
  AGGREGATE    VARCHAR2(100) NOT NULL,
  AGGREGATE_ID VARCHAR2(100) NOT NULL,
  EVENT_TYPE   VARCHAR2(100) NOT NULL,
  PAYLOAD      CLOB          NOT NULL,
  CREATED_AT   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
  SENT_AT      TIMESTAMP
);
CREATE INDEX IX_WF_OUTBOX_SENT ON WF_OUTBOX_EVENTS(SENT_AT);

CREATE TABLE WF_IDEMPOTENCY_KEYS (
  ID           NUMBER(19)    PRIMARY KEY,
  KEY          VARCHAR2(200) NOT NULL,
  FINGERPRINT  VARCHAR2(200) NOT NULL,
  CREATED_AT   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX UX_WF_IDEMPOTENCY_KEYS ON WF_IDEMPOTENCY_KEYS(KEY);

