// <auto-generated />
using System;
using Flex.Investor.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Flex.Investor.Api.Migrations
{
    [DbContext(typeof(InvestorDbContext))]
    [Migration("20250226190910_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Flex.Investor.Api.Entities.Investor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("VARCHAR2(500)")
                        .HasColumnName("ADDRESS");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("CREATEDDATE");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("DATE")
                        .HasColumnName("DATE_OF_BIRTH");

                    b.Property<string>("Email")
                        .HasColumnType("VARCHAR2(250)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(250)")
                        .HasColumnName("FULLNAME");

                    b.Property<string>("InvestmentPortfolio")
                        .HasColumnType("VARCHAR2(1000)")
                        .HasColumnName("INVESTMENT_PORTFOLIO");

                    b.Property<DateTimeOffset?>("LastModifiedDate")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("LASTMODIFIEDDATE");

                    b.Property<string>("Nationality")
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("NATIONALITY");

                    b.Property<string>("No")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(150)")
                        .HasColumnName("NO");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(250)")
                        .HasColumnName("PHONE");

                    b.HasKey("Id");

                    b.ToTable("Investors");
                });
#pragma warning restore 612, 618
        }
    }
}
