-- Create table SECURITIES
CREATE TABLE SECURITIES (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Symbol VARCHAR2(250 CHAR) NOT NULL,                          -- Mã chứng khoán
    TradePlace VARCHAR2(10 CHAR) NOT NULL,                       -- Sàn giao dịch
    Description CLOB NULL,                                       -- Mô tả
    CreatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LastModifiedDate TIMESTAMP                             
)
/

-- Insert data
INSERT INTO SECURITIES (Symbol, TradePlace, Description, CreatedDate, LastModifiedDate)
VALUES ('VCB', 'HOSE', 'Ngân hàng TMCP Ngoại thương Việt Nam - Vietcombank.', CURRENT_TIMESTAMP, NULL)
/

INSERT INTO SECURITIES (Symbol, TradePlace, Description, CreatedDate, LastModifiedDate)
VALUES ('VNM', 'HOSE', 'Vinamilk - Công ty sản xuất sữa lớn nhất Việt Nam.', CURRENT_TIMESTAMP, NULL)
/

INSERT INTO SECURITIES (Symbol, TradePlace, Description, CreatedDate, LastModifiedDate)
VALUES ('HPG', 'HOSE', 'Hòa Phát Group - Công ty sản xuất thép hàng đầu tại Việt Nam.', CURRENT_TIMESTAMP, NULL)
/
