-- Create table SECURITIES
CREATE TABLE SECURITIES (
    Id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Symbol VARCHAR2(250) NOT NULL,                          -- Mã chứng khoán
    TradePlace VARCHAR2(10) NOT NULL,                       -- Sàn giao dịch
    Description CLOB NULL,                                       -- Mô tả
    CreatedDate TIMESTAMP(7) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LastModifiedDate TIMESTAMP(7) WITH TIME ZONE                           
)
/

-- Insert data
INSERT INTO "SECURITIES" ("SYMBOL", "TRADEPLACE", "DESCRIPTION", "CREATEDDATE", "LASTMODIFIEDDATE")
VALUES ('VCB', 'HOSE', 'Ngân hàng TMCP Ngoại thương Việt Nam - Vietcombank.', CURRENT_TIMESTAMP, NULL)
/

INSERT INTO "SECURITIES" ("SYMBOL", "TRADEPLACE", "DESCRIPTION", "CREATEDDATE", "LASTMODIFIEDDATE")
VALUES ('VNM', 'HOSE', 'Vinamilk - Công ty sản xuất sữa lớn nhất Việt Nam.', CURRENT_TIMESTAMP, NULL)
/

INSERT INTO "SECURITIES" ("SYMBOL", "TRADEPLACE", "DESCRIPTION", "CREATEDDATE", "LASTMODIFIEDDATE")
VALUES ('HPG', 'HOSE', 'Hòa Phát Group - Công ty sản xuất thép hàng đầu tại Việt Nam.', CURRENT_TIMESTAMP, NULL)
/

